[package]
name = "bench"
version.workspace = true
edition.workspace = true

[dependencies]
polars = { workspace = true }
amita-base = { workspace = true }
amita-error = { workspace = true }
amita-utils = { workspace = true }