[package]
name = "bench"
version.workspace = true
edition.workspace = true

[dependencies]
polars = { workspace = true }
amita-discrete = { workspace = true }
amita-error = { workspace = true }
amita-linear = { workspace = true }
amita-universal = { workspace = true }