[package]
name = "amita-linear"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
amita-error = { workspace = true }
ndarray = { workspace = true }
linfa-linalg = { workspace = true }
polars = { workspace = true }
statrs = { workspace = true }