[package]
name = "amita-linear"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
ndarray = { workspace = true }
linfa-linalg = { workspace = true }
statrs = { workspace = true }

amita-error = { path = "../amita-error" }
amita-traits ={ path = "../amita-traits" }