[package]
name = "amita-models"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
polars = { workspace = true }

amita-base = { workspace = true }
amita-error = { workspace = true }
amita-utils = { workspace = true }